version: "3.8"

services:

  reverse-proxy:
    image: "traefik:v2.10"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.constraints=Label(`crowsnest.expose`, `true`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik-dashboard.address=:8080"
    # Dynamic Configuration
    labels:
      - "crowsnest.expose=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${CROWSNEST_HOST}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik-dashboard.entryPoints=traefik-dashboard"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

    ports:
      - "${CROWSNEST_EXTERNAL_HTTP_PORT:-80}:80"
      - "${CROWSNEST_EXTERNAL_TRAEFIK_DASHBOARD_PORT:-0}:8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
 
